apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deployment
  labels:
    app: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      labels:
        app: ansible
    spec:
      containers:
        - name: ansible
          image: packiarajd/docker-ansible:ver.2
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: sshport
              containerPort: 22
          volumeMounts:
            - name: ansible-data
              mountPath: /mnt         
      volumes:
        - name: ansible-data
          hostPath:
            path: /mnt/ansible
---
apiVersion: v1
kind: Service
metadata:
  name: ansible-service
spec:
  selector: 
    app: ansible
  type: NodePort  
  ports:
    - name: sshport
      port: 22
      targetPort: 22
      nodePort: 32022