name: CI/CD Pipeline for Docker App
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build Docker image
        shell: cmd
        run: docker build -t packiarajd/idpa:ver1 .
      - name: Display the path
        shell: cmd
        run: echo %PATH%



