name: Echo
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: W2
    steps:
      - name: Build Docker image
        shell: cmd
        run: echo %HOSTNAME%
      - name: Display the path
        shell: cmd
        run: echo %PATH%



