name: CI/CD Pipeline for Docker App
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Build Docker image
        run: docker build -t packiarajd/idpa:ver1 .

      - name: Push Docker image
        run: docker push packiarajd/idpa:ver1


